### ISSUE TITLE
Mozilla Firefox Compatiblity issue 

### ISSUE THREAD

**Issue by tryinggitfirsttime** [versatica/JsSIP#477] opened 2017-11-15 06:59 UTC
**I am using JsSIP for testing webrtc based calls. However with Mozilla Firefox 55 and higher versions,
the issue is like I am getting an error.** 

_rtcninja:ERROR:RTCPeerConnection setRemoteDescription() | error: +5ms DOMException [InvalidSessionDescriptionError: "Answer has extmap http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time at level 0 that was not present in offer."
code: 0
nsresult: 0x0]_ 

It was working fine with previous versions. Can anyone help me to fix this?

**Comment by ibc** [comment] 2017-11-17 10:42
This is not a bug in JsSIP. Indeed some versions of Firefox require that the `a=extmap` lines in the SDP offer and answer include the corresponding "send" or "recv" direction field. But Chrome does not respect that so you get into interoperability problems.

Closing this since it's not a bug in JsSIP. However, feel free to paste here both the INVITE generated by Firefox and the 200 OK from Chrome (or vice-versa).

**Closed by ibc** 2017-11-17 10:42 UTC

**Comment by tryinggitfirsttime** [comment] 2017-11-17 19:03
Ok sure.I got hold of this issue today.Some modifications made in JSsip
file the scenario work with Firefox 54+.
Thanks,
Apoorva

**Comment by ibc** [comment] 2017-11-17 19:11
> I got hold of this issue today.Some modifications made in JSsip file the scenario work with Firefox 54+.

Will you share those modifications?

**Comment by tryinggitfirsttime** [comment] 2017-11-18 00:46
Yes I vl mail you today.
Thanks.
