### ISSUE TITLE
acceptAndTerminate fails because application is in wrong state

### ISSUE THREAD

**Issue by mEkblom** [versatica/JsSIP#234] opened 2014-07-15 14:08 UTC
**Issue**: if receiving an incorrect SDP as an answer JsSIP will stop execution in that dialog, *no ACK or BYE is sent* which is should (otherwise remote SIP may continue to send OKs waiting for a reply). The application does not recover from this and media is still on presumably until the session is closed manually.

**Cause**: The internal state after receiving the answer is incorrect. State is  STATUS_INVITE_SENT, this is clearly incorrect since an OK has been received to the invitation with a remote SDP. Correct status should perhaps have been STATUS_CONFIRMED (?) or some new WACKY_LIMBO_STATUS ;-)

**Solution**: Assign a valid state (in or before acceptAndTerminate) which is accepted by Request.send(). A working suggestion is here: https://github.com/mEkblom/JsSIP/commit/7d09cbac574d2388e68fe4dd3ebd8ff195f6298f

Even though I suggested a fix for this, please consider if STATUS_CONFIRMED is the correct state and if it should be assigned where it is - *and preferably also check that this does not happen with other calls to acceptAndTerminate*.

**Comment by ibc** [comment] 2015-01-13 14:40
Closing this issue. I've not been able to reproduce it again since latest changes.

**Closed by ibc** 2015-01-13 14:40 UTC
