### ISSUE TITLE
Qualify not working for Asterisk

### ISSUE THREAD

**Issue by tpalanques** [versatica/JsSIP#445] opened 2017-06-07 12:05 UTC
I've tried the library (v3.0.12) and it's able to register to Asterisk (13.16.0) but it's unable to answer a qualify message so the status is always "UNREACHABLE".

I've attached an Asterisk CLI log file with the sip verbose enabled to see the error. Just to clarify: 10.1.1.196 is the asterisk server and 10.1.1.8 is the webphone.

[sip_debug.txt](https://github.com/versatica/JsSIP/files/1057857/sip_debug.txt)

It looks like asterisk is unable to reach the webphone because the specified transport is "ws" not "wss". 

I've made a few changes to the library to test this error, if i change the following lines in the library the qualify works well:

**line 20193:** 
instead of:     settings.contact_uri = new URI('sip', Utils.createRandomToken(8), settings.via_host, null, {transport: 'ws'});
i write:     settings.contact_uri = new URI('sip', Utils.createRandomToken(8), settings.via_host, null, {transport: 'wss'});

**line 20209:** 
instead of: contact += this.temp_gruu || 'sip:anonymous@anonymous.invalid;transport=ws';
i write: contact += this.temp_gruu || 'sip:anonymous@anonymous.invalid;transport=wss';

With this changes the registration works and the qualify works also, so it seems like the problem is there (although this is just a testing solution).

I havn't tried yet if calls do work or not, I'll let you know as soon as I try it.

**Comment by ibc** [comment] 2017-06-07 12:07
Please, questions in the mailing list. This is a well know issue in *Asterisk*. JsSIP does it OK as the [RFC 7118](https://tools.ietf.org/html/rfc7118) states. And the WS issue was fixed in latest versions of Asterisk (probably just in chap_pjsip). Please, search the mailing list and other issues.

> With this changes the registration works and the qualify works also, so it seems like the problem is there

Oh yes, the problem is there, but not in JsSIP but in old versions of Asterisk.

**Closed by ibc** 2017-06-07 12:07 UTC
